### ISSUE TITLE
How to get accelerometer data

### ISSUE THREAD

**Issue by nttgithubntt** [NateSchoolfield/blesleep#2]
Hj NateSchoolfield, firstly thanks you to support me to understand more info about mi band 4. 

From your repository, I found the way to get Gyroscope data,   I am searching there are any ways to get the accelerometer data from mi band 4 but I am still not found :( .

Could you give me some instructions to get it? tks you

**Comment by TheBeaninator** [comment]
I've been poking around, but I haven't managed to figure out how to grab the accel data.  I'll let you know if I find it though.
